export enum RootScreens {
  MAIN = "Main",
  WELCOME = "Welcome",
  HOME = "Home",
  FARMDETAIL = "FarmDetail",
  HISTORY = "History",
  MODEL = "Model",
  PROFILE = "Profile",
  REPORT = "Report",
  WEATHER = "Weather",
  UPDATEPROFILE = "UpdateProfile",
  NOTIFY = "Notify",
  STATISTIC = "Statistic",
  ADDFARM= "Add Farm",
  REGISTER1 = "Register1",
  REGISTER2 = "Register2",
  REGISTER3 = "Register3",
  REGISTER4 = "Register4",
  SPLASH = "SplashScreen",
  LOGIN = "Login",
  MAINTREE = "MainTree",
  SCHEDULE = "Schedule",
}
